
spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
     # 数据库 1
      db1:
        url: jdbc:mysql://192.168.251.61:3306/ciic_report_set?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
        username: ciic-wage
        password: ciic-wage
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
#      db1:
#        url: jdbc:mysql://localhost:3306/db1?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
#        username: root
#        password: root
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        initialSize: 5
#        minIdle: 5
#        maxActive: 20
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,localhost
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.1
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
      # 数据库 2
      db3:
        url: jdbc:mysql://192.168.251.61:3306/fc-wage-cus-v2.0?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
        username: ciic-wage
        password: ciic-wage
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
mybatis-plus:
  typeAliasesPackage: com.ciic.reporter.**.entity.**
  mapper-locations: classpath*:/mapper/**/*.xml
#==  log  ===
logging:
  config: classpath:logback.xml
